"use client";

/** AI Studio — image enhance + copy generation. Ported from legacy AIStudio.jsx. */
import { useState } from "react";
import Image from "next/image";
import { Sparkles, Upload, Wand2, ImageIcon, Tag, FileText, Megaphone, Check } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { apiClient } from "@/lib/api-client";
import { getErrorMessage } from "@/lib/api-error";

const RAW_DEMO = "https://customer-assets.emergentagent.com/job_bharat-fashion-os/artifacts/raw_demo.png";
const AFTER_DEMO = "https://customer-assets.emergentagent.com/job_bharat-fashion-os/artifacts/after_demo.png";

interface CopyResp {
  title?: string; description?: string; highlights?: string[]; tags?: string[]; campaign_copy?: string;
}

export default function AiStudioPage() {
  const [rawPreview, setRawPreview] = useState<string>(RAW_DEMO);
  const [enhanced, setEnhanced] = useState<string | null>(null);
  const [enhancing, setEnhancing] = useState(false);
  const [productName, setProductName] = useState("Hand-Block Indigo Kurta");
  const [category, setCategory] = useState("Ethnic Wear");
  const [notes, setNotes] = useState("Pure cotton, hand-block printed in Bagru, Jaipur. Festive ready.");
  const [copy, setCopy] = useState<CopyResp | null>(null);
  const [genCopy, setGenCopy] = useState(false);
  const [file, setFile] = useState<File | null>(null);

  const onFile = (f: File | null) => {
    if (!f) return;
    setFile(f);
    setRawPreview(URL.createObjectURL(f));
    setEnhanced(null);
  };

  const enhanceImage = async () => {
    setEnhancing(true); setEnhanced(null);
    try {
      if (!file) {
        await new Promise((r) => setTimeout(r, 1800));
        setEnhanced(AFTER_DEMO);
        toast.success("AI catalog shot ready");
      } else {
        const fd = new FormData();
        fd.append("file", file);
        const r = await apiClient.post<{ enhanced_base64?: string; fallback_url?: string }>(
          "/api/merchant/ai/enhance-image", fd, { headers: { "Content-Type": "multipart/form-data" } },
        );
        const data = r.data;
        if (data.enhanced_base64) setEnhanced(`data:image/png;base64,${data.enhanced_base64}`);
        else setEnhanced(data.fallback_url || AFTER_DEMO);
        toast.success("AI transformation complete");
      }
    } catch {
      toast.error("Enhancement failed — showing demo result");
      setEnhanced(AFTER_DEMO);
    } finally { setEnhancing(false); }
  };

  const generateCopy = async () => {
    setGenCopy(true); setCopy(null);
    try {
      const data = await api.merchant.aiCopy({ product_name: productName, category, notes }) as unknown as CopyResp;
      setCopy(data);
      toast.success("Copy generated by Claude 4.5");
    } catch (e) { toast.error(getErrorMessage(e)); }
    finally { setGenCopy(false); }
  };

  return (
    <div className="p-8 md:p-12 max-w-6xl">
      <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-[#E68910]/10 text-[#E68910] text-xs font-semibold mb-3">
        <Sparkles size={12} /> AI CATALOG ENGINE
      </div>
      <h1 data-testid="ai-studio-title" className="font-display text-4xl md:text-5xl font-bold text-[#1A2B4C]">Turn raw photos into editorial catalogs.</h1>
      <p className="text-[#595959] mt-2 max-w-2xl">Upload a phone shot, our AI does the rest.</p>

      <section className="mt-10 bg-white border border-[#E5E2DC] rounded-3xl p-6 md:p-8">
        <h2 className="font-display text-2xl font-bold text-[#1A2B4C] flex items-center gap-2"><ImageIcon size={20} /> Step 1 · Catalog image</h2>
        <div className="mt-6 grid md:grid-cols-2 gap-6">
          <div>
            <div className="text-[11px] uppercase tracking-widest text-[#595959] mb-2 font-semibold">Raw photo</div>
            <div className="relative aspect-[4/5] rounded-2xl overflow-hidden bg-[#FDFBF7] border-2 border-dashed border-[#E5E2DC]">
              <Image src={rawPreview} alt="raw" fill sizes="(max-width:768px) 100vw, 400px" className="object-cover" unoptimized />
            </div>
            <label data-testid="upload-zone" className="mt-3 flex items-center justify-center gap-2 px-5 py-3 rounded-full border-2 border-dashed border-[#E5E2DC] cursor-pointer hover:border-[#1A2B4C] transition">
              <Upload size={16} /> <span className="text-sm font-medium">Upload your photo</span>
              <input type="file" accept="image/*" onChange={(e) => onFile(e.target.files?.[0] ?? null)} className="hidden" />
            </label>
          </div>
          <div>
            <div className="text-[11px] uppercase tracking-widest text-[#E68910] mb-2 font-semibold">AI Studio result</div>
            <div className="relative aspect-[4/5] rounded-2xl overflow-hidden bg-[#1A2B4C] border-2 border-[#E68910]">
              {enhancing && (
                <div className="absolute inset-0 flex flex-col items-center justify-center text-white z-10 bg-[#1A2B4C]/95">
                  <Sparkles size={28} className="text-[#E68910] animate-spin mb-3" />
                  <div className="text-sm">Gemini Nano Banana<br />composing studio shot…</div>
                </div>
              )}
              {enhanced ? (
                <Image src={enhanced} alt="enhanced" fill sizes="(max-width:768px) 100vw, 400px" className="object-cover bf-fadeup" unoptimized />
              ) : (!enhancing && (
                <div className="absolute inset-0 flex items-center justify-center text-white/40 text-sm">Click &quot;Transform with AI&quot; to see the magic</div>
              ))}
              {enhanced && !enhancing && (
                <div className="absolute top-3 left-3 px-2 py-1 rounded-full bg-white/95 text-[#1A2B4C] text-[10px] font-bold flex items-center gap-1">
                  <Check size={11} /> AI ENHANCED
                </div>
              )}
            </div>
            <button onClick={enhanceImage} disabled={enhancing} data-testid="enhance-btn" className="mt-3 w-full flex items-center justify-center gap-2 px-5 py-3 rounded-full bg-[#1A2B4C] text-white font-semibold hover:bg-[#101D36] disabled:opacity-60 transition">
              <Wand2 size={16} /> {enhancing ? "Enhancing…" : "Transform with AI"}
            </button>
          </div>
        </div>
      </section>

      <section className="mt-8 bg-white border border-[#E5E2DC] rounded-3xl p-6 md:p-8">
        <h2 className="font-display text-2xl font-bold text-[#1A2B4C] flex items-center gap-2"><FileText size={20} /> Step 2 · Product copy</h2>
        <div className="mt-6 grid md:grid-cols-5 gap-6">
          <div className="md:col-span-2 space-y-3">
            <input data-testid="copy-product-name" value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="Product name" className="w-full px-4 py-3 rounded-xl border border-[#E5E2DC] outline-none focus:border-[#1A2B4C]" />
            <input data-testid="copy-category" value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Category" className="w-full px-4 py-3 rounded-xl border border-[#E5E2DC] outline-none focus:border-[#1A2B4C]" />
            <textarea data-testid="copy-notes" value={notes} onChange={(e) => setNotes(e.target.value)} rows={5} placeholder="Your notes — fabric, fit, occasion, story…" className="w-full px-4 py-3 rounded-xl border border-[#E5E2DC] outline-none focus:border-[#1A2B4C]" />
            <button onClick={generateCopy} disabled={genCopy} data-testid="generate-copy-btn" className="w-full inline-flex items-center justify-center gap-2 px-5 py-3 rounded-full bg-[#E68910] text-white font-semibold hover:bg-[#C9770E] disabled:opacity-60">
              <Sparkles size={16} /> {genCopy ? "Crafting…" : "Generate with Claude 4.5"}
            </button>
          </div>
          <div data-testid="copy-output" className="md:col-span-3 bg-[#FDFBF7] rounded-2xl p-5 min-h-72 border border-[#E5E2DC]">
            {!copy && !genCopy && (
              <div className="text-[#595959] text-sm italic">Your AI-generated title, description, hashtags, SEO meta and campaign hook will appear here.</div>
            )}
            {genCopy && <div className="text-[#1A2B4C] flex items-center gap-2"><Sparkles size={16} className="animate-spin text-[#E68910]" /> Composing premium copy…</div>}
            {copy && (
              <div className="space-y-4 bf-fadeup">
                <div><div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1">Title</div><h3 className="font-display text-xl font-bold text-[#1A2B4C]">{copy.title}</h3></div>
                <div><div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1">Description</div><p className="text-sm text-[#1C1C1C] leading-relaxed">{copy.description}</p></div>
                {copy.highlights && copy.highlights.length > 0 && (
                  <div><div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1">Highlights</div>
                    <ul className="text-sm text-[#1C1C1C] space-y-1">{copy.highlights.map((h) => <li key={h} className="flex gap-2"><Check size={14} className="text-[#4F7363] mt-0.5 shrink-0" />{h}</li>)}</ul>
                  </div>
                )}
                {copy.tags && copy.tags.length > 0 && (
                  <div><div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1 flex items-center gap-1"><Tag size={11} /> Hashtags</div>
                    <div className="flex flex-wrap gap-1.5">{copy.tags.map((t) => <span key={t} className="px-2.5 py-1 rounded-full bg-white border border-[#E5E2DC] text-xs">#{String(t).replace(/^#/, "")}</span>)}</div>
                  </div>
                )}
                {copy.campaign_copy && (
                  <div><div className="text-[10px] uppercase tracking-widest text-[#E68910] font-semibold mb-1 flex items-center gap-1"><Megaphone size={11} /> Campaign hook</div><p className="text-sm italic text-[#1A2B4C]">&ldquo;{copy.campaign_copy}&rdquo;</p></div>
                )}
              </div>
            )}
          </div>
        </div>
      </section>
    </div>
  );
}
